#!/usr/bin/env bash
#bash script to rewrite my loclhost IP

# Store the original /etc/hosts file
original_hosts="/etc/hosts"

# Backup the original hosts file
sudo cp "$original_hosts" "${original_hosts}.bak"

# Update localhost and facebook.com entries
sudo sed -i 's/127.0.0.1[[:space:]]\+localhost/127.0.0.2 localhost/g' "$original_hosts"
sudo sed -i 's/\bfacebook.com\b/8.8.8.8 facebook.com/g' "$original_hosts"

# Output success message
echo "Configuration completed successfully. Remember to revert localhost to 127.0.0.1 if needed."
