#!/usr/bin/env bash
#bash script to ping for host
# Check if the script is provided with an argument
if [ "$#" -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Extract the IP address from the argument
ip_address="$1"

# Ping the IP address 5 times
ping -c 5 "$ip_address"
