#!/usr/bin/env bash
# Install the Uncomplicated Firewall (UFW) and set up port forwarding on web-01

# Update package information
sudo apt-get update -y

# Install UFW firewall
sudo apt-get install ufw -y

# Enable UFW
sudo ufw enable

# Set default policies
sudo ufw default deny incoming -y
sudo ufw default allow outgoing -y

# Allow SSH (Port 22)
sudo ufw allow 22/tcp

# Allow HTTPS (Port 443)
sudo ufw allow 443/tcp

# Allow HTTP (Port 80)
sudo ufw allow 80/tcp

# Allow port forwarding from 8080 to 80
sudo ufw route allow proto tcp from any to any port 8080
